### ISSUE TITLE
Drop specifier "inline" for callback functions

### ISSUE THREAD

**Issue by elfring** [xant/libhl#14]
Three callback functions are assigned to [attributes of the variable "keys_callbacks_default"](https://github.com/xant/libhl/blob/bdb0409dc5d0406657d19d973e4a9b7601704d9c/src/binheap.c#L118 "Initialisation for 'keys_callbacks_default'").
I find the usage of [the specifier "inline"](http://www.drdobbs.com/the-new-c-inline-functions/184401540 "The New C: Inline Functions") inappropriate for them because a callable address will be needed in this use case.

**Comment by xant** [comment]
af4340ab4ec57a9278ae016d514fb5c284ad9645
