### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [xant/libhl#16]
How do you think about to benefit from [parallel build trees](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html "Parallel build trees (VPATH)") also for your software?
Would you like to [support out-of-source](http://cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F "Out-of-source build trees") ([VPATH](https://www.gnu.org/software/make/manual/html_node/General-Search.html "Search path for prerequisites")) builds?

**Comment by xant** [comment]
It makes sense ... at this point I'm considering using autotools (which I would prefer to cmake).
The problem is time to work on it :P I'll try and see what it means in terms of effort to convert the project and make use of autoconf/automake

**Comment by xant** [comment]
fbc7142a347b3ebaea488a554f3e6a7fc936bd9d
