### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [xant/libhl#17]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/xant/libhl/blob/6b3538d34793a9ab518994e14e2263c6c2aeb8d2/configure.ac#L30 "Configuration checks")?

**Comment by xant** [comment]
added ... even if it's a bit annoying I needed to add an extra m4 file to the repo to have it available
(I thought it would have been some standard autconf macro)

**Comment by elfring** [comment]
Should I eventually check your approach before any changes are committed and published here?

**Comment by xant** [comment]
yes ... a patch here would be appreciated ... so I also see how what is the proper way of including such extra autowhatever macros

**Comment by elfring** [comment]
* Did you look at any configuration examples from other software libraries?
* How do you think about to store a script like "ax_pthread.m4" into the subdirectory "m4" eventually?
