### ISSUE TITLE
Reuse of "libtool"?

### ISSUE THREAD

**Issue by elfring** [xant/libhl#19]
I suggest to [reuse the software "libtool"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Libtool.htm Libtool usage").
Would you like to [add the call of the macro "LT_INIT"](https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html "The LT_INIT macro")" to [your build specification](https://github.com/xant/libhl/blob/6b3538d34793a9ab518994e14e2263c6c2aeb8d2/configure.ac#L12 "Configuration checks")?

**Comment by xant** [comment]
libtool is now used in the build process (wrapping calls to the actual compiler and linker)...
even if I'm unsure it's the right way of using it
