### ISSUE TITLE
Include to a library

### ISSUE THREAD

**Issue by fatihky** [xant/libhl#21]
Hi! I written a library. It is open source. I included some files from your library. What should I do now(including your license etc.)?

**Comment by xant** [comment]
Hi there. Sure no problem, the license of libhl is LGPL so I guess that should be preserved.
Apart from the license I would also put a note somewhere in your project pointing out where the external code comes from.
Let me know if you find any issues with libhl code.

Cheers,
Andrea.

**Comment by fatihky** [comment]
Thanks much. I will point out.
