### ISSUE TITLE
Tons of key-value pairs.

### ISSUE THREAD

**Issue by lxyscls** [xant/libhl#28]
Hello, I am looking for a hashtable which can hold millions or even more key-value pairs. Can this hashtable hold such payload, and give a good performance when there is some rebalance?

**Comment by xant** [comment]
I've been using it in a project where very large hashtables were being used.
Also consider sharding if you want to scale horizontally.

**Comment by sudashannon** [comment]
> Hello, I am looking for a hashtable which can hold millions or even more key-value pairs. Can this hashtable hold such payload, and give a good performance when there is some rebalance?

老哥用的咋样

**Comment by lxyscls** [comment]
> > Hello, I am looking for a hashtable which can hold millions or even more key-value pairs. Can this hashtable hold such payload, and give a good performance when there is some rebalance?
> 
> 老哥用的咋样

我用khash + 读写锁，还行，就是内存比较吃，https://github.com/attractivechaos/klib
