### ISSUE TITLE
Queue issue

### ISSUE THREAD

**Issue by Pccccccc** [xant/libhl#29]
hi, author. I use create 5 thread to pop queue's arg, there are 10000 args that push to queue. But sometimes, the process will be crash. And from the crash log, i see that queue will call refcnt free and then process crash.

**Comment by xant** [comment]
Can you please provide the code hitting the issue? Also a stack trace could be helpful

**Comment by xant** [comment]
I'm not able to reproduce, please reopen this issue if you can reproduce and providing some example code.

**Comment by xant** [comment]
also,  the scenario you describe is actually being tested  (check the unit tests distributed with the repo)

``` 
  6 Threaded queue (5 pull-workers, 10000 items pushed to the queue from the main thread)                ok
```

It succeeds consistently for me ... so if you should probably check your code first (or let me see it)
