### ISSUE TITLE
ht_foreach_value return remove, will lose item

### ISSUE THREAD

**Issue by cxm1997** [xant/libhl#34]
ht_create(65536, 65536, NULL);

TEST_1 remove all item:
add 100000 item to hashtable, 
before ht_foreach_value, ht_count()  is 100000
then ht_foreach_value. in callback function return HT_ITERATOR_REMOVE, record entry callback function count is 51261
after, ht_count() is 48739

TEST_2 contine all item:
add 100000 item to hashtable, 
before ht_foreach_value, ht_count()  is 100000
then ht_foreach_value,  in callback function return HT_ITERATOR_CONTINUE, record entry callback function count is 100000
after, ht_count() is 100000

actually, I want to traverse all items and delete them
so, when ht_foreach_value callback return HT_ITERATOR_REMOVE, will lose item.

**Comment by cxm1997** [comment]
use master code to test

**Comment by cxm1997** [comment]
`#include <stdio.h>
#include <string.h>
#include "hashtable.h"

static int g_continue = 0;
static int g_remove = 0;

ht_iterator_status_t test_continue(hashtable_t *table, void *value, size_t vlen, void *user)
{
    g_continue++;
    return HT_ITERATOR_CONTINUE;
}

ht_iterator_status_t test_remove(hashtable_t *table, void *value, size_t vlen, void *user)
{
    g_remove++;
    return HT_ITERATOR_REMOVE;
}

int main(int argc, char *argv[])
{
    int i = 0;
    hashtable_t *table = NULL;

    table = ht_create(65536, 65536, NULL);

    printf("S0 %ld\n", ht_count(table));

    for (i = 0; i < 100000; i++) {
        char k[21] = {0};

        sprintf(k, "%d", i);
        ht_set(table, (void *)k, strlen(k), "test", strlen("test"));
    }

    printf("S1 %ld\n", ht_count(table));

    ht_foreach_value(table, test_continue, NULL);

    printf("S2 %ld\n", ht_count(table));

    ht_foreach_value(table, test_remove, NULL);

    printf("S3 %ld\n", ht_count(table));

    printf("continue %ld\n", g_continue);
    printf("remove %ld\n", g_remove);

    return 0;
}`

**Comment by cxm1997** [comment]
#include <stdio.h>
#include <string.h>
#include "hashtable.h"

static int g_continue = 0;
static int g_remove = 0;

ht_iterator_status_t test_continue(hashtable_t *table, void *value, size_t vlen, void *user)
{
    g_continue++;
    return HT_ITERATOR_CONTINUE;
}

ht_iterator_status_t test_remove(hashtable_t *table, void *value, size_t vlen, void *user)
{
    g_remove++;
    return HT_ITERATOR_REMOVE;
}

int main(int argc, char *argv[])
{
    int i = 0;
    hashtable_t *table = NULL;

    table = ht_create(65536, 65536, NULL);

    printf("S0 %ld\n", ht_count(table));

    for (i = 0; i < 100000; i++) {
        char k[21] = {0};

        sprintf(k, "%d", i);
        ht_set(table, (void *)k, strlen(k), "test", strlen("test"));
    }

    printf("S1 %ld\n", ht_count(table));

    ht_foreach_value(table, test_continue, NULL);

    printf("S2 %ld\n", ht_count(table));

    ht_foreach_value(table, test_remove, NULL);

    printf("S3 %ld\n", ht_count(table));

    printf("continue %ld\n", g_continue);
    printf("remove %ld\n", g_remove);

    return 0;
}

**Comment by cxm1997** [comment]
`
#include <stdio.h>
#include <string.h>
#include "hashtable.h"

static int g_continue = 0;
static int g_remove = 0;

ht_iterator_status_t test_continue(hashtable_t *table, void *value, size_t vlen, void *user)
{
    g_continue++;
    return HT_ITERATOR_CONTINUE;
}

ht_iterator_status_t test_remove(hashtable_t *table, void *value, size_t vlen, void *user)
{
    g_remove++;
    return HT_ITERATOR_REMOVE;
}

int main(int argc, char *argv[])
{
    int i = 0;
    hashtable_t *table = NULL;

    table = ht_create(65536, 65536, NULL);

    printf("S0 %ld\n", ht_count(table));

    for (i = 0; i < 100000; i++) {
        char k[21] = {0};

        sprintf(k, "%d", i);
        ht_set(table, (void *)k, strlen(k), "test", strlen("test"));
    }

    printf("S1 %ld\n", ht_count(table));

    ht_foreach_value(table, test_continue, NULL);

    printf("S2 %ld\n", ht_count(table));

    ht_foreach_value(table, test_remove, NULL);

    printf("S3 %ld\n", ht_count(table));

    printf("continue %ld\n", g_continue);
    printf("remove %ld\n", g_remove);

    return 0;
}
`

**Comment by cxm1997** [comment]
test code at [https://gist.github.com/cxm1997/06f99190be5e553f5b476286f333ad14](url)

run result:
S0 0
S1 100000
S2 100000
S3 48739
continue 100000
remove 51261

**Comment by xant** [comment]
Thanks!
The fix is in 1ab7aec75fdb3e65e11aefbd6ea017e7dcdcd8bf
I also added a test which was reproducing the issue before fixing the code in hashtable.c
